#ifndef PANEL_MT5_TYPES_MQH
#define PANEL_MT5_TYPES_MQH

enum ENUM_TRADE_DIRECTION
{
   TRADE_DIRECTION_SELL = 0,
   TRADE_DIRECTION_BUY = 1
};

enum ENUM_PANEL_ORDER_TYPE
{
   PANEL_ORDER_TYPE_MARKET = 0,
   PANEL_ORDER_TYPE_LIMIT = 1,
   PANEL_ORDER_TYPE_STOP = 2
};

#endif
